package model.pojo;
// Generated Jun 6, 2017 11:15:00 PM by Hibernate Tools 4.3.1



/**
 * Nhanvien generated by hbm2java
 */
public class Nhanvien  implements java.io.Serializable {


     private Integer idnhanvien;
     private String hoten;
     private String tendn;
     private String matkhau;
     private String role;

    public Nhanvien() {
    }

    public Nhanvien(String hoten, String tendn, String matkhau, String role) {
       this.hoten = hoten;
       this.tendn = tendn;
       this.matkhau = matkhau;
       this.role = role;
    }
   
    public Integer getIdnhanvien() {
        return this.idnhanvien;
    }
    
    public void setIdnhanvien(Integer idnhanvien) {
        this.idnhanvien = idnhanvien;
    }
    public String getHoten() {
        return this.hoten;
    }
    
    public void setHoten(String hoten) {
        this.hoten = hoten;
    }
    public String getTendn() {
        return this.tendn;
    }
    
    public void setTendn(String tendn) {
        this.tendn = tendn;
    }
    public String getMatkhau() {
        return this.matkhau;
    }
    
    public void setMatkhau(String matkhau) {
        this.matkhau = matkhau;
    }
    public String getRole() {
        return this.role;
    }
    
    public void setRole(String role) {
        this.role = role;
    }




}


