package model.pojo;
// Generated Jun 4, 2017 8:03:44 AM by Hibernate Tools 4.3.1



/**
 * Quanly generated by hbm2java
 */
public class Quanly  implements java.io.Serializable {


     private Integer idquanly;
     private String hoten;
     private String tendangnhap;
     private String matkhau;

    public Quanly() {
    }

	
    public Quanly(String tendangnhap, String matkhau) {
        this.tendangnhap = tendangnhap;
        this.matkhau = matkhau;
    }
    public Quanly(String hoten, String tendangnhap, String matkhau) {
       this.hoten = hoten;
       this.tendangnhap = tendangnhap;
       this.matkhau = matkhau;
    }
   
    public Integer getIdquanly() {
        return this.idquanly;
    }
    
    public void setIdquanly(Integer idquanly) {
        this.idquanly = idquanly;
    }
    public String getHoten() {
        return this.hoten;
    }
    
    public void setHoten(String hoten) {
        this.hoten = hoten;
    }
    public String getTendangnhap() {
        return this.tendangnhap;
    }
    
    public void setTendangnhap(String tendangnhap) {
        this.tendangnhap = tendangnhap;
    }
    public String getMatkhau() {
        return this.matkhau;
    }
    
    public void setMatkhau(String matkhau) {
        this.matkhau = matkhau;
    }




}


