package model.pojo;
// Generated Jun 6, 2017 11:15:00 PM by Hibernate Tools 4.3.1



/**
 * Sanpham generated by hbm2java
 */
public class Sanpham  implements java.io.Serializable {


     private Integer id;
     private String tenSp;
     private String mieuTa;
     private Long gia;
     private Integer soLuong;

    public Sanpham() {
    }

    public Sanpham(String tenSp, String mieuTa, Long gia, Integer soLuong) {
       this.tenSp = tenSp;
       this.mieuTa = mieuTa;
       this.gia = gia;
       this.soLuong = soLuong;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getTenSp() {
        return this.tenSp;
    }
    
    public void setTenSp(String tenSp) {
        this.tenSp = tenSp;
    }
    public String getMieuTa() {
        return this.mieuTa;
    }
    
    public void setMieuTa(String mieuTa) {
        this.mieuTa = mieuTa;
    }
    public Long getGia() {
        return this.gia;
    }
    
    public void setGia(Long gia) {
        this.gia = gia;
    }
    public Integer getSoLuong() {
        return this.soLuong;
    }
    
    public void setSoLuong(Integer soLuong) {
        this.soLuong = soLuong;
    }




}


