package model.pojo;
// Generated Jun 4, 2017 8:03:44 AM by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * Sanpham generated by hbm2java
 */
public class Sanpham  implements java.io.Serializable {


     private Integer id;
     private String tenSp;
     private String mieuTa;
     private BigDecimal gia;
     private Integer soLuong;

    public Sanpham() {
    }

	
    public Sanpham(String tenSp) {
        this.tenSp = tenSp;
    }
    public Sanpham(String tenSp, String mieuTa, BigDecimal gia, Integer soLuong) {
       this.tenSp = tenSp;
       this.mieuTa = mieuTa;
       this.gia = gia;
       this.soLuong = soLuong;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getTenSp() {
        return this.tenSp;
    }
    
    public void setTenSp(String tenSp) {
        this.tenSp = tenSp;
    }
    public String getMieuTa() {
        return this.mieuTa;
    }
    
    public void setMieuTa(String mieuTa) {
        this.mieuTa = mieuTa;
    }
    public BigDecimal getGia() {
        return this.gia;
    }
    
    public void setGia(BigDecimal gia) {
        this.gia = gia;
    }
    public Integer getSoLuong() {
        return this.soLuong;
    }
    
    public void setSoLuong(Integer soLuong) {
        this.soLuong = soLuong;
    }




}


